language: node_js

node_js:
- '6'

cache:
  directories:
    - node_modules

before_install:
- npm install -g hexo

before_script:
  - git clone --branch master https://github.com/yodahuang/yodahuang.github.io public

script:
  - npm run build

after_success:
  - cd public
  - git config user.name "Yanda Bot"
  - git config user.email "ward11sdo@qq.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push https://$DEPLOY_REPO@github.com/yodahuang/yodahuang.github.io.git master

branches:
  only:
    - src
