# Site settings
title: "Huang's Lab"
email: ward11sdo@qq.com
description: "A place for fun."
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "以本来面目凝视世间万物."
title_image: "http://i.imgur.com/LKWk35x.jpg"
google_analytics: "UA-65976996-1"
disqus_account: yodahuang
github_repository: https://github.com/yodahuang/
addthis_id: ra-55c202ff6f7d5886
post_limit: 5

# Social usernames/URLs
twitter_username: ward11sdo
github_username:  yodahuang
linkedin_link: http://www.renren.com/337956378/
google_plus_link: https://plus.google.com/u/1/113522853895289094772/posts
stackoverflow_link: http://www.renren.com/337956378/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> Yanda Huang</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/yodahuang/yodahuang.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
